apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-configmap
data:
  N8N_PORT: "3008"
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
  N8N_SECURE_COOKIE: "false"
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_SSL_ENABLED: "true"
  DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED: "false"
