apiVersion: v1
kind: Service
metadata:
  labels:
    app: n8n
  name: n8n
spec:
  ports:
    - name: "3008"
      port: 3008
      protocol: TCP
      targetPort: 3008
  selector:
    app: n8n
  type: LoadBalancer
